name: Docker Image CI

on:
  push:
    branches: [ "release" ]

jobs:

  build:

    name: Build Docker Image

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bgogolin/tipping-bot

  push:

    name: Push Docker image to Docker Hub

    runs-on: ubuntu-latest

    needs: build

    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push the Docker image (amd64)
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.amd
        push: true
        tags: bgogolin/tipping-bot:amd64

  # notify:

  #   name: Notify Techulus about deployment

  #   runs-on: ubuntu-latest

  #   needs: [build, push, deploy]

