name: Docker Image CI

on:
  push:
    branches: [ "release" ]

jobs:

  build:

    name: Build Docker Image

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/tipping-bot

  push:
    env:
        ARCHITECTURE: 'amd64'

    name: Push Docker image to Docker Hub

    runs-on: ubuntu-latest

    needs: build

    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push the Docker image for ${{env.ARCHITECTURE}}
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.${{env.ARCHITECTURE}}
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/tipping-bot:${{env.ARCHITECTURE}}
          ${{ secrets.DOCKERHUB_USERNAME }}/tipping-bot:latest

  # notify:

  #   name: Notify Techulus about deployment

  #   runs-on: ubuntu-latest

  #   needs: [build, push, deploy]

