name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    name: Build Docker Image

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag antonengelhardt/kicktipp-bot

  push:

    name: Push Docker image to Docker Hub
    
    runs-on: ubuntu-latest

    needs: build

    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push the Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: antonengelhardt/kicktipp-bot:latest

  deploy:

    name: Deploy to Server

    runs-on: ubuntu-latest

    needs: [build, push]

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            docker pull antonengelhardt/kicktipp-bot:latest
            docker stop kicktipp-bot
            docker rm kicktipp-bot
            docker run -d --name kicktipp-bot -e KICKTIPP_EMAIL=$KICKTIPP_EMAIL -e KICKTIPP_PASSWORD=$KICKTIPP_PASSWORD -e KICKTIPP_NAME_OF_COMPETITION=$KICKTIPP_NAME_OF_COMPETITION -e ZAPIER_URL=$ZAPIER_URL antonengelhardt/kicktipp-bot:latest
